config/routes.rb
Rails.application.routes.draw do
  root "images#index"

  resources :images

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :carrier_wave_image, CarrierWaveImageUploader

  has_attached_file :paperclip_image, styles: { thumb: "100x100#" }
  validates_attachment_content_type :paperclip_image, content_type: ["image/jpeg", "image/png"]
  validates_attachment_file_name :paperclip_image, matches: [/png\Z/, /jpe?g\Z/]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  def index
    @images = Image.all
  end

  # GET /images/1
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  def create
    @image = Image.new(image_params)

    if @image.save
      redirect_to images_path, notice: 'Image was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /images/1
  def update
    if @image.update(image_params)
      redirect_to @image, notice: 'Image was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /images/1
  def destroy
    @image.destroy
    redirect_to images_url, notice: 'Image was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def image_params
      params[:image].permit(:carrier_wave_image, :paperclip_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

  <p>
    <%= f.label :carrier_wave_image, "CarrierWave Upload" %>
    <%= f.file_field :carrier_wave_image %>
  </p>

  <p>
    <%= f.label :carrier_wave_image, "Paperclip Upload" %>
    <%= f.file_field :paperclip_image %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Images</h1>

<%= link_to 'New Image', new_image_path %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <% if image.carrier_wave_image.file %>
          <td><%= image_tag image.carrier_wave_image.thumb %></td>
        <% else %>
          <td><%= image_tag image.paperclip_image.url(:thumb) %></td>
        <% end %>
        <td><%= link_to 'X', image, method: :delete   %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImagetragickRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>